# Generated by Django 6.0.2 on 2026-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('user', 'User')], default='author', max_length=20),
        ),
    ]
