# Generated by Django 6.0.2 on 2026-04-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0003_comment_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='ads/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
            },
        ),
    ]
