# Generated by Django 6.0.2 on 2026-04-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0004_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
