# Generated by Django 6.0.2 on 2026-04-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0006_like_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user')},
        ),
    ]
