# Generated by Django 6.0.2 on 2026-04-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0008_alter_authuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Obunachi',
                'verbose_name_plural': 'Obunachilar',
            },
        ),
    ]
