# Generated by Django 6.0.2 on 2026-04-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0009_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
