# Generated by Django 6.0.2 on 2026-04-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0010_alter_category_slug_alter_post_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_end',
            field=models.CharField(default='#2471a3', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='color_start',
            field=models.CharField(default='#1a6fa8', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fas fa-folder', max_length=100),
        ),
    ]
