# Generated by Django 6.0.2 on 2026-04-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0012_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='color_start',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='color_end',
        ),
    ]
