# Generated by Django 6.0.2 on 2026-04-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0013_rename_color_start_category_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
