# Generated by Django 6.0.2 on 2026-04-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0015_post_video_post_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
        migrations.AddField(
            model_name='postcontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('title', 'Title'), ('image', 'Image'), ('quote', 'Quote'), ('stat', 'Stat'), ('info', 'Info Box'), ('video', 'Video')], max_length=10),
        ),
    ]
