# Generated by Django 6.0.2 on 2026-04-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0017_alter_post_short_description_alter_postcontent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
