# Generated by Django 6.0.2 on 2026-04-25 18:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0019_alter_post_short_description_alter_postcontent_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=1000),
        ),
    ]
