# Generated by Django 6.0.2 on 2026-04-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0020_alter_post_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('umumiy', 'Umumiy savol'), ('hamkorlik', 'Hamkorlik'), ('reklama', 'Reklama'), ('xato', 'Xato bildirish'), ('boshqa', 'Boshqa')], default='umumiy', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='authuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
