# Generated by Django 6.0.2 on 2026-04-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0021_contactmessage_authuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='extra_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
