# Generated by Django 6.0.2 on 2026-04-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0022_contactmessage_extra_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='Kanal username (@ovoza_news) yoki ID (-100xxxxxxxxxx)', max_length=100)),
                ('send_title', models.BooleanField(default=True, verbose_name='Sarlavha')),
                ('send_image', models.BooleanField(default=True, verbose_name='Rasm')),
                ('send_description', models.BooleanField(default=True, verbose_name='Qisqacha matn')),
                ('send_category', models.BooleanField(default=True, verbose_name='Kategoriya')),
                ('send_author', models.BooleanField(default=False, verbose_name='Muallif')),
                ('send_link', models.BooleanField(default=True, verbose_name='Havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Telegram sozlamalari',
                'verbose_name_plural': 'Telegram sozlamalari',
            },
        ),
    ]
