# Generated by Django 6.0.2 on 2026-04-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0023_telegramsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek (Lotin)"), ('uz-cyrl', 'Ўзбек (Кирил)'), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=10),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='channel_id',
            field=models.CharField(help_text='Faqat username formatida: @OvozaNewsPage — t.me/... emas!', max_length=100),
        ),
    ]
