# Generated by Django 6.0.2 on 2026-04-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovoza', '0024_post_language_alter_telegramsettings_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
